import type { NextPage } from "next";
import Head from "next/head";
import React, { FormEvent, useRef, useState } from "react";
import { fetchFeedbackAPI } from "../api/fetchFeedback";
import { FeedbackModel } from "../models/FeedbackModel";

const Home: NextPage = () => {
  const [feedbackList, setFeedbackList] = useState<FeedbackModel[] | null>(
    null
  );
  const emailInputRef = useRef<HTMLInputElement>(null);
  const feedbackInputRef = useRef<HTMLTextAreaElement>(null);

  const handleSubmitForm = async (event: FormEvent) => {
    event.preventDefault();
    const email = emailInputRef.current?.value ?? "";
    const feedback = feedbackInputRef.current?.value ?? "";
    const response = await fetchFeedbackAPI({
      method: "POST",
      body: { email, feedback },
    });

    console.log(response);
  };

  const handleLoadData = async () => {
    const response = await fetchFeedbackAPI<FeedbackModel[]>();

    setFeedbackList(response.data);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Home Page</h1>
        <form onSubmit={handleSubmitForm}>
          <div>
            <label>Your email address</label>
            <input type="email" id="email" ref={emailInputRef} />
          </div>
          <div>
            <label>Feedback</label>
            <textarea rows={5} id="feedback" ref={feedbackInputRef} />
          </div>
          <button>Send</button>
        </form>
        <button onClick={handleLoadData}>Load data</button>
        <h4>List</h4>
        <ul>
          {feedbackList?.map((feedback) => {
            return (
              <li key={feedback.id}>
                <div>{feedback.email}</div>
                <div>{feedback.feedback}</div>
              </li>
            );
          })}
        </ul>
      </main>
    </div>
  );
};

export default Home;
